const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const roles={citizen:{name:'Cidadão',icon:'assets/bluePlayerIcon.png',desc:'Sem ação noturna. Ajude a cidade a encontrar o Assassino.'},assassin:{name:'Assassino',icon:'assets/knifeIcon.png',desc:'À noite, escolha um jogador para eliminar.'},doctor:{name:'Médico',icon:'assets/medkitIcon.png',desc:'À noite, escolha alguém para proteger.'},detective:{name:'Detetive',icon:'assets/magIcon.png',desc:'À noite, investigue um jogador e descubra secretamente se ele é o Assassino.'},clown:{name:'Palhaço',icon:'assets/bananaIcon.png',desc:'Vence imediatamente se for eliminado pela votação do dia.'}};
const colors=['blue','red','green','yellow','purple','orange','pink','cyan','brown','gray','salmon','black'];
let state={players:[],phase:'setup',round:1,currentReveal:0,nightStep:0,nightActions:{assassin:null,doctor:null,detective:null},lastNight:null,winner:null,voteTarget:null};
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function roleList(n){let r=['assassin','doctor','detective','clown'];while(r.length<n)r.push('citizen');return r.slice(0,n)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function updateRolePreview(){const n=+$('#playerCount').textContent;const counts=roleList(n).reduce((o,r)=>(o[r]=(o[r]||0)+1,o),{});$('#rolePreview').innerHTML=Object.entries(counts).map(([r,c])=>'<span class="role-chip '+(r!=='citizen'?'special':'')+'">'+roles[r].name+(c>1?' ×'+c:'')+'</span>').join('')}
function buildPlayersForm(){const n=+$('#playerCount').textContent;$('#playersForm').innerHTML=Array.from({length:n},(_,i)=>'<div class="player-row"><img class="color-select" src="assets/'+colors[i%colors.length]+'PlayerIcon.png"><input class="player-name" maxlength="14" value="Jogador '+(i+1)+'"></div>').join('')}
function startGame(){const names=$$('.player-name').map((el,i)=>({id:i,name:el.value.trim()||('Jogador '+(i+1)),color:colors[i%colors.length],alive:true,role:null}));const rs=shuffle(roleList(names.length));names.forEach((p,i)=>p.role=rs[i]);state.players=names;state.currentReveal=0;renderReveal();show('roleScreen')}
function renderReveal(){const p=state.players[state.currentReveal];$('#revealPlayerName').textContent=p.name;$('#roleCard').classList.add('hidden');$('#nextRevealBtn').classList.add('hidden');$('#revealRoleBtn').classList.remove('hidden')}
function reveal(){const p=state.players[state.currentReveal],r=roles[p.role];$('#roleCard').innerHTML='<img src="'+r.icon+'"><h3>'+r.name+'</h3><p>'+r.desc+'</p>';$('#roleCard').classList.remove('hidden');$('#revealRoleBtn').classList.add('hidden');$('#nextRevealBtn').classList.remove('hidden')}
function nextReveal(){state.currentReveal++;if(state.currentReveal>=state.players.length){startNight();return}renderReveal()}
function startNight(){state.phase='night';state.round=1;state.nightStep=0;state.nightActions={assassin:null,doctor:null,detective:null};show('gameScreen');renderGame()}
function alive(){return state.players.filter(p=>p.alive)}
function targetButtons(){return alive().map(p=>'<button class="target" data-target="'+p.id+'"><img src="assets/'+p.color+'PlayerIcon.png"><span>'+p.name+'</span></button>').join('')}
function renderBoard(){ $('#playersBoard').innerHTML=state.players.map(p=>'<div class="player-card '+(p.alive?'':'dead')+'"><img src="assets/'+p.color+'PlayerIcon.png"><div><span class="name">'+p.name+'</span><span class="status">'+(p.alive?'VIVO':'FORA')+'</span></div></div>').join('')}
function renderGame(){renderBoard();$('#phaseBadge').textContent=state.phase==='night'?'NOITE':'DIA';$('#roundLabel').textContent=state.round;if(state.phase==='night')renderNight();else renderDay()}
function renderNight(){const steps=['assassin','doctor','detective'];const role=steps[state.nightStep];if(!role){finishNight();return}const r=roles[role];$('#phaseTitle').textContent='Chame o '+r.name;$('#phaseText').textContent=role==='assassin'?'Escolha o alvo do Assassino.':role==='doctor'?'Escolha quem o Médico protege.':'Escolha quem o Detetive investiga.';$('#nightArea').innerHTML='<div class="action-card"><h3>'+r.name+'</h3><p>'+r.desc+'</p><div class="target-grid">'+targetButtons()+'</div></div>';$('#dayArea').classList.add('hidden');$('#nightArea').classList.remove('hidden');$('#advancePhaseBtn').textContent='CONFIRMAR / PRÓXIMO';$$('.target').forEach(b=>b.onclick=()=>selectNight(role,+b.dataset.target))}
function selectNight(role,id){state.nightActions[role]=id;$$('.target').forEach(b=>b.classList.toggle('selected',+b.dataset.target===id))}
function finishNight(){const a=state.nightActions.assassin,d=state.nightActions.doctor;const victim=a!=null&&a!==d?state.players.find(p=>p.id===a):null;state.lastNight=victim?victim.name:null;if(victim)victim.alive=false;state.nightStep=0;state.phase='day';if(victim&&victim.role==='clown'){state.winner='clown';renderWinner();return}renderGame()}
function renderDay(){const victim=state.lastNight;$('#phaseTitle').textContent='A cidade acorda!';$('#phaseText').textContent=victim?victim+' foi eliminado durante a noite.':'Ninguém foi eliminado durante a noite.';$('#nightArea').classList.add('hidden');$('#dayArea').classList.remove('hidden');$('#dayArea').innerHTML='<div class="action-card"><h3>☀️ DISCUSSÃO</h3><p>Conversem. Quando estiverem prontos, escolham alguém para a votação.</p><div class="target-grid">'+targetButtons()+'</div><button class="pixel-btn primary wide" id="voteBtn">ELIMINAR VOTADO</button></div>';$('#advancePhaseBtn').textContent='ENCERRAR DIA';$$('.target').forEach(b=>b.onclick=()=>{$$('.target').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.voteTarget=+b.dataset.target});$('#voteBtn').onclick=resolveVote}
function resolveVote(){if(state.voteTarget==null)return;const p=state.players.find(x=>x.id===state.voteTarget);p.alive=false;state.voteTarget=null;if(p.role==='clown'){state.winner='clown';renderWinner();return}if(checkWinner())return;state.round++;state.phase='night';state.nightStep=0;state.nightActions={assassin:null,doctor:null,detective:null};renderGame()}
function checkWinner(){const a=alive(),ass=a.filter(p=>p.role==='assassin').length;if(!ass){state.winner='city';renderWinner();return true}if(a.length<=ass){state.winner='assassin';renderWinner();return true}return false}
function renderWinner(){show('gameScreen');$('#phaseBadge').textContent='FIM';$('#roundLabel').textContent=state.round;$('#nightArea').classList.add('hidden');$('#dayArea').classList.add('hidden');$('#phaseTitle').textContent=state.winner==='city'?'A CIDADE VENCE!':state.winner==='clown'?'O PALHAÇO VENCE!':'O ASSASSINO VENCE!';$('#phaseText').textContent='A partida terminou. Veja os papéis abaixo.';$('#playersBoard').innerHTML=state.players.map(p=>'<div class="player-card '+(p.alive?'':'dead')+'"><img src="assets/'+p.color+'PlayerIcon.png"><div><span class="name">'+p.name+'</span><span class="status">'+roles[p.role].name+'</span></div></div>').join('');$('#advancePhaseBtn').textContent='NOVA PARTIDA';$('#advancePhaseBtn').onclick=()=>location.reload()}
$('#newGameBtn').onclick=()=>{show('setupScreen');updateRolePreview()};$('#howBtn').onclick=()=>show('howScreen');$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#minusPlayers').onclick=()=>{$('#playerCount').textContent=Math.max(5,+$('#playerCount').textContent-1);updateRolePreview()};$('#plusPlayers').onclick=()=>{$('#playerCount').textContent=Math.min(12,+$('#playerCount').textContent+1);updateRolePreview()};$('#continueSetup').onclick=()=>{buildPlayersForm();show('playersScreen')};$('#startGameBtn').onclick=startGame;$('#revealRoleBtn').onclick=reveal;$('#nextRevealBtn').onclick=nextReveal;$('#advancePhaseBtn').onclick=()=>{if(state.phase==='night'){state.nightStep++;renderNight()}else{state.phase='night';state.nightStep=0;state.nightActions={assassin:null,doctor:null,detective:null};renderGame()}};$('#restartBtn').onclick=()=>{if(confirm('Sair da partida?'))location.reload()};updateRolePreview();